In [1]:
import pandas as pd

In [14]:
# df1_gln = pd.read_csv('/Volumes/LaCie/phospho_white_list/PXD006449/2021-08-24-14-06-06/Task2-search/Individual File Results/20130426_SK_SA_marta_phospho_24_gln_1_PSMs.psmtsv',sep='\t')

df1_gln = pd.read_csv('/Volumes/LaCie/phospho_white_list/PXD006449/2021-08-24-14-06-06/Task2-search/Individual File Results/20130426_SK_SA_marta_phospho_24_1_PSMs.psmtsv',sep='\t')
df1['dataset'] = 'PXD006449'

df1_gln_oligo = pd.read_csv('/Volumes/LaCie/phospho_white_list/PXD006449/2021-08-24-14-06-06/Task2-search/Individual File Results/20130426_SK_SA_marta_phospho_24_gln_oligo_1_Peptides.psmtsv',sep='\t')

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (22,23,24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

# Find differential peptides
Using total ion current as proxy for intensity

In [15]:
list1 = pd.Series(list(set(df1_gln['Base Sequence']) & set(df1_gln_oligo['Base Sequence'])))
# intersection = formated_df1[formated_df1['Base Sequence'].isin(list1)]
list1

0           HNSFADFLQAHLHTADLER
1                  RGDFFYHSENPK
2       EVGKDVSDEKLRDYIWNTLNSGR
3                    HGVFVGSAMR
4                  DLFHCVSFTLPR
                 ...
3170                NRDHDTFLAVR
3171       RQVSASELHTSGILGPETLR
3172              HKTGPNLHGLFGR
3173             AIEALHGHELRPGR
3174             HGYIGEFEIIDDHR
Length: 3175, dtype: object

In [16]:
df1_gln_oligo = df1_gln_oligo[df1_gln_oligo['Base Sequence'].isin(list1)][['Base Sequence', 'Total Ion Current']]
df1_gln_oligo = df1_gln_oligo.groupby(['Base Sequence'])['Total Ion Current'].apply(lambda x: ','.join(x.astype(str))).reset_index()


df1_gln_oligo

                       Base Sequence                      Total Ion Current
0           AAEPLTELEESIETVVTTFFTFAR                     147928.83289000002
1           AAFQIISQVISEATEQVLATTVGK                     1407901.2401100001
2                      AAGTLYTYPENWR                           509975.83032
3                    AAHEALGQFCCALHK                           1353957.3064
4                  AAIDWFDGKEFSGNPIK                      860456.2691700001
...                              ...                                    ...
3170                   YTIHSQLEHLQSK                            271833.2677
3171  YTLPPGVDPTQVSSSLSPEGTLTVEAPMPK  235381.35803000003,226415.30346999998
3172                     YVDIAIPCNNK                          1182813.19482
3173                     YVGSMVADVHR       2148519.2675799998,1338327.67615
3174                   YYQTIGNHASYYK                      545822.5837399999

[3175 rows x 2 columns]

In [17]:
#differential peptides
df1_gln = df1_gln[df1_gln['Base Sequence'].isin(list1)][['Base Sequence', 'Total Ion Current']]
df1_gln = df1_gln.groupby(['Base Sequence'])['Total Ion Current'].apply(lambda x: ','.join(x.astype(str))).reset_index()

df1_gln

,Base Sequence,Total Ion Current
0,AAEPLTELEESIETVVTTFFTFAR,"339676.8645,745586.3457"
1,AAFQIISQVISEATEQVLATTVGK,2384483.82202
2,AAGTLYTYPENWR,595687.09998
3,AAHEALGQFCCALHK,1878595.005
4,AAIDWFDGKEFSGNPIK,"977404.599,541695.36694"
...,...,...
3170,YTIHSQLEHLQSK,827475.32568
3171,YTLPPGVDPTQVSSSLSPEGTLTVEAPMPK,"374244.53735,343204.77295,237775.99706999998,2..."
3172,YVDIAIPCNNK,1580189.5280799998
3173,YVGSMVADVHR,"2826003.56104,1983266.85657"
3174,YYQTIGNHASYYK,1351523.74719

In [18]:
df_new = pd.merge(df1_gln, df1_gln_oligo, on='Base Sequence',suffixes=('_gln', '_gln_oligo'))

df_new

,Base Sequence,Total Ion Current_gln,Total Ion Current_gln_oligo
0,AAEPLTELEESIETVVTTFFTFAR,"339676.8645,745586.3457",147928.83289000002
1,AAFQIISQVISEATEQVLATTVGK,2384483.82202,1407901.2401100001
2,AAGTLYTYPENWR,595687.09998,509975.83032
3,AAHEALGQFCCALHK,1878595.005,1353957.3064
4,AAIDWFDGKEFSGNPIK,"977404.599,541695.36694",860456.2691700001
...,...,...,...
3170,YTIHSQLEHLQSK,827475.32568,271833.2677
3171,YTLPPGVDPTQVSSSLSPEGTLTVEAPMPK,"374244.53735,343204.77295,237775.99706999998,2...","235381.35803000003,226415.30346999998"
3172,YVDIAIPCNNK,1580189.5280799998,1182813.19482
3173,YVGSMVADVHR,"2826003.56104,1983266.85657","2148519.2675799998,1338327.67615"
3174,YYQTIGNHASYYK,1351523.74719,545822.5837399999

In [24]:
gln = df_new['Total Ion Current_gln'].str.split(',', expand=True)
gln_oligo = df_new['Total Ion Current_gln_oligo'].str.split(',', expand=True)

gln_oligo['peptide'] = df_new['Base Sequence']
gln['peptide'] = df_new['Base Sequence']

gln_oligo = gln_oligo.set_index('peptide').T
gln_oligo = gln_oligo.astype(float)
gln_oligo['dataset'] = "gln_oligo"
gln_oligo = gln_oligo.dropna(thresh=2, axis=1)

gln = gln.set_index('peptide').T
gln = gln.astype(float)
gln['dataset'] = "gln"
gln = gln.dropna(thresh=2, axis=1)

In [25]:
list2 = pd.Series(list(set(gln.columns[:-1]) & set(gln_oligo.columns[:-1])))

list2

0      ANDHQGFYLLNSIIEHMPPESVDQYRK
1                 ERFSPPRHELSPPQKR
2      HTGPGILSMANAGPNTNGSQFFICTAK
3                 TPVSPVKFSPGDFWGR
4                      SIIGMIDMFHK
                  ...
298                  HLAEHSPYYEAMK
299               HLSPYATLTVGDSSHK
300                   VKTPEMIIQKPK
301                    MKPILLQGHER
302             GASLHHGRPHLGSVPDFR
Length: 303, dtype: object

In [26]:
gln_oligo = gln_oligo[gln_oligo.columns.intersection(list2)]
gln = gln[gln.columns.intersection(list2)]

gln['dataset'] = "gln"
gln_oligo['dataset'] = "gln_oligo"

In [27]:
ttest_df = pd.concat([gln,gln_oligo],axis=0)
ttest_df

peptide,AAPEASSPPASPLQHLLPGK,ADKDYHFKVDNDENEHQLSLR,AGKPVICATQMLESMIK,AGTLSITEFADMLSGNAGGFRSR,AHAWPSPYKDYEVK,AHTPTPGIYMGR,ALESPERPFLAILGGAK,ALSDHHIYLEGTLLKPNMVTPGHACTQK,AMGIMNSFVNDIFER,ANDHQGFYLLNSIIEHMPPESVDQYRK,...,YHGNVMLLR,YHLGMYHR,YHSLAPMYYR,YMHSGPVVAMVWEGLNVVK,YPIEHGIITNWDDMEK,YPIEHGIITNWDDMEKIWHHTFYNELR,YPIEHGIVTNWDDMEKIWHHTFYNELR,YTLPPGVDPTQVSSSLSPEGTLTVEAPMPK,YVGSMVADVHR,dataset
0,6.018658e+06,5.623208e+06,2.949244e+06,4.595982e+06,1.125918e+07,2.216583e+06,5.106117e+06,6.983676e+06,4.182182e+06,1.478546e+06,...,2.304975e+06,3.229335e+06,2.556654e+06,744418.37903,1.142374e+07,1.441668e+08,9.119716e+05,374244.53735,2.826004e+06,gln
1,5.674709e+06,1.918180e+07,2.915134e+06,1.127197e+07,7.552102e+05,2.819824e+06,7.013806e+06,3.525381e+07,3.232795e+06,6.140711e+05,...,9.652217e+05,2.099986e+06,1.717341e+06,678580.93762,7.264229e+06,1.016433e+08,2.008040e+07,343204.77295,1.983267e+06,gln
2,7.632028e+06,5.523088e+07,2.336685e+06,NaN,3.605878e+05,2.768040e+06,9.455395e+06,3.885622e+06,3.287390e+06,1.155205e+06,...,2.059510e+06,1.782424e+06,1.755985e+06,NaN,4.900430e+06,1.937250e+07,2.731861e+06,237775.99707,NaN,gln
3,1.043492e+06,4.964371e+06,1.109643e+06,NaN,1.950743e+06,2.447512e+06,2.879214e+06,2.470288e+06,1.548488e+07,1.330026e+06,...,NaN,7.401570e+05,1.394202e+06,NaN,2.752006e+07,4.384386e+07,1.766823e+07,246969.32178,NaN,gln
4,2.454522e+06,3.550983e+06,1.986864e+06,NaN,5.611899e+06,3.832409e+06,5.849297e+06,3.155484e+06,2.467089e+06,4.967787e+05,...,NaN,NaN,2.038796e+06,NaN,7.105646e+07,1.418261e+07,8.280693e+06,NaN,NaN,gln
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,8.741704e+05,6.870736e+05,5.525820e+05,8.883375e+06,1.742336e+06,1.937921e+06,3.774659e+06,3.980668e+05,1.612532e+06,1.366791e+05,...,1.072650e+06,1.075953e+06,1.088327e+06,252734.20117,7.137091e+05,8.597844e+06,4.832967e+05,226415.30347,1.338328e+06,gln_oligo
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.893552e+06,3.210162e+05,NaN,...,NaN,NaN,NaN,NaN,NaN,2.199240e+06,NaN,NaN,NaN,gln_oligo
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.414682e+07,NaN,NaN,NaN,gln_oligo
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.093693e+05,NaN,NaN,NaN,gln_oligo
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.272417e+06,NaN,NaN,NaN,gln_oligo

In [28]:
wrap_ttest(ttest_df, mincount=2, label_column='dataset',return_all=True)

                        Comparison  P_Value
0     ALSDHHIYLEGTLLKPNMVTPGHACTQK      1.0
1                 LNSHMNALHLGSQANR      1.0
2                     MLSSAYISDHMK      1.0
3                 PRPPGRPVSGHGMDSR      1.0
4               PVSSAASVYAGAGGSGSR      1.0
5                QSSATSSFGGLGGGSVR      1.0
6          RPAPAVSPGSWKPGPPGSPRPWK      1.0
7                    RPHTPTPGIYMGR      1.0
8     SGDAAIVDMVPGKPMCVESFSDYPPLGR      1.0
9                      SIIGMIDMFHK      1.0
10                SLPSSPLRLGSYKAQK      1.0
11                 SNMDNMFESYINNLR      1.0
12       SPGTGPSPFSSSLGHLNHLGGSLDR      1.0
13         SPSPPLPTHIPPEPPRTPPFPAK      1.0
14  SVVLMSHLGRPDGVPMPDKYSLEPVAVELK      1.0
15      TMHGHDHNVSSVAIMPNGDHIVSASR      1.0
16          TMIISPERLDPFADGGKTPDPK      1.0
17          TSNKPLMIIHHLDECPHSQALK      1.0
18        VIHDNFGIVEGLMTTVHAITATQK      1.0
19               VNGLPSPTHSAHCSFYR      1.0
20                VNLQNNPGAMEHFHMK      1.0
21                    VVDLMAHMASKE      1.0
22                   LESGMQNMSIHTK      1.0
23                  YHGHSMSDPGVSYR      1.0
24              KYEDICPSTHNMDVPNIK      1.0
25      KFGDPVVQSDMKHWPFQVINDGDKPK      1.0
26                 AMGIMNSFVNDIFER      1.0
27    CPEALFQPSFLGMESCGIHETTFNSIMK      1.0
28   EHPWEVMPDLYFYRDPEEIEKEEQAAAEK      1.0
29               EPDCFKDIVNMLMHHDR      1.0
30      GGMGSGGLATGIAGGLAGMGGIQNEK      1.0
31      GMGGHGYGGAGDASSGFHGGHFVHMR      1.0
32       GMSVSDLADKLSTDDLNSLIAHAHR      1.0
33                 GPSWDPFRDWYPHSR      1.0
34                       HEHQLMLMR      1.0
35             HFVDSHHQKPVNAIIEHVR      1.0
36          HGTDLWIDNMSSAVPNHSPEKK      1.0
37                    HGVHMMVATPGR      1.0
38     HHHTDGAYFGTGFPHMLFMVHPEYRPK      1.0
39                    HLEMNPHFGSHR      1.0
40                       HMYHSLYLK      1.0
41                     HQGVMVGMGQK      1.0
42            HVMTRLGEKLSDEEVDEMIR      1.0
43                  HWPFMVVNDAGRPK      1.0
44            IKPHLMSQELPEDWDKQPVK      1.0
45                     ISMPDFDLHLK      1.0
46                        ISSSSFSR      1.0
47                  KSAPATGGVKKPHR      1.0
48     YPIEHGIITNWDDMEKIWHHTFYNELR      1.0

In [12]:
import pandas as pd
import numpy as np
import scipy.stats
import statsmodels.stats.multitest
import operator
import warnings

def wrap_ttest(df, label_column, comparison_columns=None, alpha=.05, equal_var=True, return_all=False, correction_method='bonferroni', mincount=3, pval_return_corrected=True, quiet=False):
    try:
#         import pdb;pdb.set_trace()
        '''Verify precondition that label column exists and has exactly 2 unique values'''
        label_values = df[label_column].unique()
        if len(label_values) != 2:
            print("Incorrectly Formatted Dataframe! Label column must have exactly 2 unique values.")
            return None

        '''Partition dataframe into two sets, one for each of the two unique values from the label column'''
        partition1 = df.loc[df[label_column] == label_values[0]]
        partition2 = df.loc[df[label_column] == label_values[1]]

        '''If no comparison columns specified, use all columns except the specified labed column'''
        if not comparison_columns:
            comparison_columns = list(df.columns)
            comparison_columns.remove(label_column)

        '''Determine the number of real valued columns on which we will do t-tests'''
        number_of_comparisons = len(comparison_columns)

        '''Store comparisons and p-values in two arrays'''
        comparisons = []
        pvals = []

        '''Loop through each comparison column, perform the t-test, and record the p-val'''

        for column in comparison_columns:
            if len(partition1[column].dropna(axis=0)) <= mincount:
                continue
            elif len(partition2[column].dropna(axis=0)) <= mincount:
                continue
            else:

                group1 = partition1[column].dropna(axis=0)
                group2 = partition2[column].dropna(axis=0)

                if (np.std(group1) == 0 or np.std(group2) == 0) and not quiet:
                    warnings.warn(f"At least one group for column {column} had a standard deviation of zero.", StDevWarning)

                stat, pval = scipy.stats.ttest_ind(
                    a=group1,
                    b=group2, 
                    equal_var=equal_var
                )

                if pd.notna(pval):
                    comparisons.append(column)
                    pvals.append(pval)
                elif not quiet:
                    warnings.warn(f"pval for column {column} was NaN. pval dropped.", PvalWarning)

        if len(pvals) == 0: # None of the groups had enough members to pass the mincount
            raise InvalidParameterError("No groups had enough members to pass mincount; no tests run.")

        '''Correct for multiple testing to determine if each comparison meets the new cutoff'''
        results = statsmodels.stats.multitest.multipletests(pvals=pvals, alpha=alpha, method=correction_method)
        reject = results[0]

        '''Format results in a pandas dataframe'''
        results_df = pd.DataFrame(columns=['Comparison','P_Value'])

        '''If return all, add all comparisons and p-values to dataframe'''
        if return_all:
            if pval_return_corrected:
                results_df['Comparison'] = comparisons
                results_df['P_Value'] = results[1]

            else:
                results_df['Comparison'] = comparisons
                results_df['P_Value'] = pvals

            '''Else only add significant comparisons'''
        else:
            for i in range(0, len(reject)):
                if reject[i]:
                    if pval_return_corrected:
                        results_df = results_df.append({'Comparison':comparisons[i],'P_Value':results[1][i]}, ignore_index=True)
                    else:
                        results_df = results_df.append({'Comparison':comparisons[i],'P_Value':pvals[i]}, ignore_index=True)


        '''Sort dataframe by ascending p-value'''
        results_df = results_df.sort_values(by='P_Value', ascending=True)
        results_df = results_df.reset_index(drop=True)

        '''If results df is not empty, return it, else return None'''
        if len(results_df) > 0:
            return results_df
        else:
            return None


    except:
        print("Incorrectly Formatted Dataframe!")
        return None

In [ ]:
stop

In [217]:
xls = pd.ExcelFile('/Volumes/LaCie/phospho_white_list/PXD000472/Supplementary_Dataset_1.xlsx')
df2 = pd.read_excel(xls, 'Phosphopeptide Features')
df2['dataset'] = 'PXD000472'

In [218]:
list1 = pd.Series(list(set(df1_gln['Base Sequence']) & set(df2['Peptide'])))

In [219]:
list2 = pd.Series(list(set(df1['Base Sequence']) & set(df2['Peptide'])))

In [220]:
list3 = pd.Series(list(set(list1) & set(list2)))
list3

0                         GEFSASPMLK
1      STAQQELDGKPASPTPVIVASHTANKEEK
2                     ISAPNVDFNLEGPK
3                        GSLASLDSLRK
4              ILGSASPEEEQEKPILDRPTR
                   ...
461        KQPPVSPGTALVGSQKEPSEVPTPK
462               SGPKPFSAPKPQTSPSPK
463                     RQSPSPSTRPIR
464                     RFSPSQVPIQTR
465                KGVEPSPSPIKPGDIKR
Length: 466, dtype: object

In [221]:
#format and sort by intensities

In [222]:
formated_df1 = df1[['Base Sequence','File Name','Scan Retention Time','Total Ion Current']]


#sort by intesnity
formated_df1 = formated_df1.sort_values('Total Ion Current', ascending = False)

#get the intersection
formated_df1 = formated_df1[formated_df1['Base Sequence'].isin(list3)]
formated_df1

,Base Sequence,File Name,Scan Retention Time,Total Ion Current
1507,KQSLGELIGTLNAAK,20130426_SK_SA_marta_phospho_8_1,158.66619,2.390171e+08
1860,KQSLGELIGTLNAAK,20130426_SK_SA_marta_phospho_8_1,158.30857,1.890453e+08
1,KQSLGELIGTLNAAK,20130426_SK_SA_marta_phospho_8_1,158.66493,1.525524e+08
2,KQSLGELIGTLNAAK,20130426_SK_SA_marta_phospho_8_1,158.30507,1.459836e+08
2536,GSPHYFSPFRPY,20130426_SK_SA_marta_phospho_8_1,141.11578,1.163195e+08
...,...,...,...,...
14827,TPAAAAAMNLASPR,20130426_SK_SA_marta_phospho_8_1,67.65210,8.731443e+04
9285,ATSNVFAMFDQSQIQEFK,20130426_SK_SA_marta_phospho_8_1,213.93844,8.091869e+04
12747,SSSPGKPQAVSSLNSSHSR,20130426_SK_SA_marta_phospho_8_1,27.77124,7.952812e+04
14747,VLSPLIIK,20130426_SK_SA_marta_phospho_8_1,162.31195,6.398548e+04
12714,ISAPNVDFNLEGPK,20130426_SK_SA_marta_phospho_8_1,174.85167,5.794101e+04

In [223]:
import statistics
def average_intesnities(row):
    return statistics.mean([row['Incubator_1'],row['Incubator_2'],row['Incubator_3'],row['Incubator_4']])


formated_df2 = df2[['Peptide','protein','best_tR','m_z', 'Incubator_1','Incubator_2','Incubator_3','Incubator_4']]
formated_df2

    
formated_df2['intensity'] = formated_df2.apply(average_intesnities, axis=1)


#sort by intesnity
formated_df2 = formated_df2.sort_values('intensity', ascending = False)

#get the intersection
formated_df2 = formated_df2[formated_df2['Peptide'].isin(list3)]
formated_df2

<ipython-input-223-96fba38bdaa3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  formated_df2['intensity'] = formated_df2.apply(average_intesnities, axis=1)

,Peptide,protein,best_tR,m_z,Incubator_1,Incubator_2,Incubator_3,Incubator_4,intensity
2310,SSSPAPADIAQTVQEDLR,Ras GTPase-activating protein-binding protein ...,62.3792,982.952369,1.252595e-02,8.615613e-03,1.147564e-02,1.261267e-02,1.130747e-02
2336,ATAPQTQHVSPMR,Elongation factor 1-delta OS=Homo sapiens GN=E...,18.6268,501.897849,8.142464e-03,9.667102e-03,1.125570e-02,1.493482e-02,1.100002e-02
1901,KQSLGELIGTLNAAK,Triosephosphate isomerase OS=Homo sapiens GN=T...,57.5193,811.930299,1.161734e-02,9.112456e-03,1.071865e-02,1.127366e-02,1.068053e-02
2498,AGDLLEDSPKRPK,Hepatoma-derived growth factor OS=Homo sapiens...,20.1823,502.583919,9.839676e-03,9.713256e-03,9.544477e-03,1.218152e-02,1.031973e-02
1708,QLSSGVSEIR,Heat shock protein beta-1 OS=Homo sapiens GN=H...,30.9040,578.274749,8.477861e-03,9.392086e-03,7.738816e-03,7.980447e-03,8.397302e-03
...,...,...,...,...,...,...,...,...,...
309,RQSFASLALR,Ankyrin-3 OS=Homo sapiens GN=ANK3 PE=1 SV=3,43.3074,614.814689,2.888865e-06,3.135647e-10,3.294486e-06,4.711291e-10,1.546034e-06
234,ATSNVFAMFDQSQIQEFK,Myosin regulatory light chain 12B OS=Homo sapi...,83.6675,1125.961949,3.769396e-10,3.135647e-10,1.029486e-06,4.112015e-06,1.285548e-06
203,AITSLLGGGSPK,Nipped-B-like protein OS=Homo sapiens GN=NIPBL...,48.7343,590.803789,3.769396e-10,1.342057e-06,1.105853e-06,1.931158e-06,1.094861e-06
230,LDIDSPPITAR,Pyruvate kinase isozymes M1/M2 OS=Homo sapiens...,45.8613,639.311319,3.769396e-10,3.385245e-06,3.249641e-10,4.711291e-10,8.466044e-07
283,RASLSDIGFGKLETYVK,Cyclin-dependent kinase 18 OS=Homo sapiens GN=...,60.6082,655.335449,3.769396e-10,3.135647e-10,1.296282e-06,1.314450e-06,6.528556e-07